#!/bin/env bash

# Simple-ZRAM is a simple script to create and enable zram swap devices
# Copyright (C) 2024  Michael Schaecher <michaelleeschaecher@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Test if we are root
function verifyRoot () { test "$(id -u)" -eq 0 || { echo "This script must be run as root" ; exit 1 ; } ;}

# Log messages to syslog
function sysLog () { logger -t "${_appName}" "${@}"; }

function startSwap () {

        local priority device

        # Does a zram device already exist?
        ! zramctl -n | grep -q '/dev/zram' || { sysLog "device already exists ( $(zramctl -n) )" ; exit 0 ;}

        # Validate the compression algorithm is supported.
        case "${_swapAlgorithm}" in
            lzo|zstd|lz4    ) ;;
            *               ) sysLog "Unsupported compression algorithm: ${_swapAlgorithm}" ; exit 1 ;;
        esac

        # Make sure that the required amount of RAM is available (32Gb minimum and 50% free)
        (( _totalRAM > 33554432 )) || { sysLog "$((_totalRAM / 1024000))GB RAM available, 32GB required."; exit 1; }
        (( _availableRAM > 50 )) || { sysLog "Only ${_availableRAM}% RAM available, 50% required."; exit 1; }

        # If more then 1 zram device then override swap priority
        test "${_swapDevices}" -lt "1" || priority=$(( _swapPriority / _swapDevices ))

        # Create the zram devices
        for ((i = 0; i < _swapDevices; i++)); do
            device=$(zramctl --size "${_swapSize}G" --algorithm "$_swapAlgorithm" --find) || {
                log "Failed to create zram device."; exit 1;
            }

            mkswap -L SWAP "$device" || { log "Failed to mkswap: $device"; exit 1; }

            if ! swapon --priority "${priority}" "$device" 2>/dev/null; then
                if ! swapon "$device"; then
                    log "Failed to enable swap: $device"; exit 1;
                fi
            fi

            log "ZRAM enabled: $device | Size: ${_swapSize}G | Algorithm: $_swapAlgorithm"
        done

}

function stopSwap () {

    zramctl -n | awk '{print $1}' | while read -r device; do
        swapoff "$device" || { sysLog "Failed to disable swap: $device"; exit 1; }
        zramctl --reset "$device" || { sysLog "Failed to reset: $device"; exit 1; }

        sysLog "ZRAM reset: $device"
    done

}

set -euo pipefail

# shellcheck disable=SC1091
source /etc/simple-zram.conf

_appName=simple-zram
_appVersion="$(cat /usr/share/docs/${_appName}/version 2>/dev/null || echo "unknown")"

_totalRAM="$(awk '/MemTotal:/ {print $2}' /proc/meminfo)"
_usedRAM="$(awk '/Active:/ {print $2}' /proc/meminfo)"

# Do some math to calculate if more then 50% of the RAM is used
_availableRAM="$(( 100 - (( _usedRAM * 100 ) / _totalRAM) ))"

# Default values for the script
_swapSize=${SWAP_SIZE:-"2"}
_swapAlgorithm=${SWAP_ALGORITHM:-"lzo"}
_swapDevices="${SWAP_DEVICES:-"1"}"
_swapPriority=${SWAP_PRIORITY:-"100"}

_getRAM="$(free -h | grep -i 'mem')"
_getSwap="$(free -h | grep -i 'swap')"

_copyRightInfo="$(cat <<EOF
Copyright (C) 2024 Michael Schaecher  <michaelleeschaecher@gmail.com> GNU v3 License
EOF
)"

_versionInfo="$(cat <<EOF
${_appName} - version: ${_appVersion}
${_copyRightInfo}
EOF
)"

_helpInfo="$(cat <<EOF
${_versionInfo}
This script creates and enables a zram swap device with the following parameters:

Usage: ${_appName} [OPTIONS]

Options:
  start                   Start the zram swap device with the configured parameters
  stop                    Stop the zram swap device and reset it
  info                    Show version and configuration information
  help                    Show this help message

${_copyRightInfo}
EOF
)"

_zramInfo="$(cat <<EOF
${_versionInfo}

ITEM                        VALUE
-----------------------------------------------------------

Total RAM:                  $(echo "${_getRAM}" | awk '{print $2}')
Used RAM:                   $(echo "${_getRAM}" | awk '{print $3}')
Available RAM:              ${_availableRAM}%

Devices Number:             ${_swapDevices}
ZRAM Devices:               $(zramctl -n | awk '{print $1}')

Swap Size:                  $(echo "${_getSwap}" | awk '{print $2}')
Swap Usage:                 $(echo "${_getSwap}" | awk '{print $3}')

Compression Algorithm:      ${_swapAlgorithm}

EOF
)"

case "${1}" in
    start                   ) verifyRoot ; startSwap          ;;
    stop                    ) verifyRoot ; stopSwap           ;;
    info                    ) echo "${_zramInfo}"    ; exit 0 ;;
    version                 ) echo "${_versionInfo}" ; exit 0 ;;
    help                    ) echo "${_helpInfo}"    ; exit 0 ;;
    *                       )
        echo "Invalid option: ${1}"
        echo "Use '${_appName} help' for usage information"
        exit 1
    ;;
esac

exit 0
