#!/bin/bash

set -e

case "${1}" in
    configure)
        if systemctl is-active --quiet simple-zram.service; then
            systemctl daemon-reload
        else
            systemctl restart simple-zram.service
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument: ${1}" >&2
        exit 0
esac
