#!/bin/sh

set -e

case "$1" in
	configure|abort-upgrade|abort-deconfigure|abort-remove)
		# This is the postinst script for zswapd package.
		deb-systemd-helper unmask 'zswapd.service' >/dev/null || true
		if deb-systemd-helper --quiet was-enabled 'zswapd.service'; then
			deb-systemd-helper enable 'zswapd.service' >/dev/null || true
		else
			deb-systemd-helper update-state 'zswapd.service' >/dev/null || true
		fi
		systemctl --system daemon-reload 2> /dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'zswapd.service' >/dev/null || true

		# check if the ZRAM module is loaded
		if ! lsmod | grep -q '^zram'; then
			modprobe zram || echo "Failed to load zram module."
		fi
	;;
	*)
		echo "postinst: Invalid argument $1. Use 'configure|abort-upgrade|abort-deconfigure|abort-remove'."
		exit 1
	;;
esac
