#!/bin/bash

set -e

case "${1}" in
    configure|upgrade|reinstall|install             )
        # Restart the systemd-modules-load service to ensure the zram module is loaded
        systemctl restart systemd-modules-load.service

        # Check if simple-zram is already enabled if so reload the daemon
        case "$(systemctl is-enabled simple-zram.service)" in
            enabled             ) systemctl daemon-reload ; systemctl restart simple-zram.service ;;
            disabled            ) systemctl enable --now simple-zram.service                      ;;
            *                   )
                echo "simple-zram service is in an unknown state, please check manually." >&2
            ;;
        esac

    ;;
    *                                               )
        echo "postinst called with unknown argument: ${1}" >&2
    ;;
esac

exit 0
