#!/bin/env bash

# zswapd - A script to manage zram swap devices on Linux systems
# shellcheck disable=SC2329
function sign-handler () {

    local _signal; _signal="${1:-SIGINT}"

    case "${_signal}" in
        SIGINT|SIGTERM|SIGQUIT )
            event-log "info" "Received signal: ${_signal}. Stopping ${appName} service ... " ;;
        *                      ) event-log "warning" "Received unknown signal: ${_signal}"    ;;
    esac

    exit 0

}

function event-log () {

    local eventType="${1:-unknown}"
    local eventMessage="${2:-No message provided}"

    case "$eventType" in
        info|warning|error|critical )
            logger -t "${appName}" -p user."$eventType" "$eventMessage"
            [[ "$eventType" == "error" || "$eventType" == "critical" ]] && exit
        ;;
        *                           ) logger -t "${appName}" -p user.unknown "${eventMessage}" ;;
    esac

}

function start-swap () {

    local setPriority
    local zramDevice

    # Does a zram device already exist?
    ! zramctl -n | grep -q '/dev/zram' || { event-log "info" "ZRAM device already exists." ; exit 0 ;}

    # Validate the compression algorithm is supported.

    checkAlgorithm=("lzo" "zstd" "lz4")

    [[ " ${checkAlgorithm[*]} " == *" $swapAlgorithm "* ]] ||
    event-log "error" "Unsupported compression algorithm: $swapAlgorithm"

    # Make sure that the required amount of RAM is available (32Gb minimum and 50% free)
    (( totalRAM > 33554432 )) || event-log "error" "Insufficient RAM: $totalRAM bytes available, 32GB required."

    (( availableRAM > 50 )) || event-log "error" "Insufficient RAM: $availableRAM% available, 50% required."

    # If more then 1 zram device then override swap priority
    test "${swapDevices}" -lt "1" || setPriority=$(( swapPriority / swapDevices ))

    # Create the zram devices
    for ((i = 0; i < swapDevices; i++)); do
        zramDevice=$(zramctl --size "${swapSize}G" --algorithm "$swapAlgorithm" --find) ||
        event-log "error" "Failed to create zram device."

        mkswap -L SWAP "$zramDevice" || event-log "error" "Failed to mkswap on device: $zramDevice"

        ! swapon "$zramDevice" && ! swapon --priority "$setPriority" "$zramDevice" 2>/dev/null &&
        event-log "error" "Failed to enable swap on device: $zramDevice"

        event-log "info"m "ZRAM device created and enabled: $zramDevice with priority $setPriority"

    done

}

function stop-swap () {

    zramctl -n | awk '{print $1}' | while read -r device; do

        swapoff "$device" || event-log "error" "Failed to disable swap on device: $device"
        zramctl --reset "$device" || event-log "error" "Failed to reset zram device: $device"

        event-log "info" "ZRAM device reset: $device"

    done

}

function edit-conf () {

    echo "Opening configuration file for editing..."

    # Open the configuration file in the default editor
    if test -n "$defaultEditor" ; then
        "$defaultEditor" /etc/zswapd.conf ||
        event-log "error" "Failed to open configuration file with editor: $defaultEditor"
    else
        event-log "error" "No default editor set. Please set the EDITOR environment variable."
    fi

}

# Uncomment for debugging
#set -euo pipefail

# shellcheck disable=SC1091
source /etc/zswapd.conf 2>/dev/null || { echo "Missing configuration file: /etc/zswapd.conf" ; exit 1 ; }

appName="zswapd"
appVersion="$(cat /usr/share/doc/${appName}/version 2>/dev/null || echo "unknown")"

totalRAM="$(awk '/MemTotal:/ {print $2}' /proc/meminfo)"
usedRAM="$(awk '/Active:/ {print $2}' /proc/meminfo)"

# Do some math to calculate if more then 50% of the RAM is used
availableRAM="$(( 100 - (( usedRAM * 100 ) / totalRAM) ))"

# Default values for the script
swapSize=${SWAP_SIZE:-"2"}
swapAlgorithm=${SWAP_ALGORITHM:-"lzo"}
swapDevices="${SWAP_DEVICES:-"1"}"
swapPriority=${SWAP_PRIORITY:-"100"}

getRAM="$(free -h | grep -i 'mem')"
getSwap="$(free -h | grep -i 'swap')"

defaultEditor="${EDITOR:-"nano"}"

# Trap errors and log them
trap sign-handler SIGINT SIGTERM SIGQUIT

copyRightInfo="$(cat <<EOF
Copyright (C) 2024 Michael Schaecher  <michaelleeschaecher@gmail.com> GNU v3 License
EOF
)"

versionInfo="$(cat <<EOF
${appName} - version: ${appVersion}
${copyRightInfo}
EOF
)"

helpInfo="$(cat <<EOF
${versionInfo}
This script creates and enables a zram swap device with the following parameters:

Usage: ${appName} [OPTIONS]

Options:
    start                   Start the zram swap device with the configured parameters
    stop                    Stop the zram swap device and reset it
    status                  Show the current status of the zram swap device
    config                  Edit the configuration file for the zram swap device
    version                 Show the version information
    help                    Show this help message

${copyRightInfo}
EOF
)"

_zramInfo="$(cat <<EOF
${versionInfo}

ITEM                        VALUE
-----------------------------------------------------------

Total RAM:                  $(echo "${getRAM}" | awk '{print $2}')
Used RAM:                   $(echo "${getRAM}" | awk '{print $3}')
Available RAM:              ${availableRAM}%

Devices Number:             ${swapDevices}
ZRAM Devices:               $(zramctl -n | awk '{print $1}')

Swap Size:                  $(echo "${getSwap}" | awk '{print $2}')
Swap Usage:                 $(echo "${getSwap}" | awk '{print $3}')

Service:                    $(systemctl is-active --quiet "${appName}.service" &&
                                echo "active" || echo "inactive")

Compression Algorithm:      ${swapAlgorithm}

EOF
)"

[[ $# -eq 0 && "$1" == "help" ]] && { echo "${helpInfo}" ; exit 0 ; }
[[ $# -eq 0 && "$1" == "version" ]] && { echo "${versionInfo}" ; exit 0 ; }

# No options provided
[[ $# -eq 0 ]] && { echo "No options provided. Use '${appName} help' for usage information." ; exit 1 ; }

# Ensure the script is run as root.
if (( "$(id -u)" == "0" )) ; then
    case "${1}" in
        start                   ) start-swap                      ;;
        stop                    ) stop-swap                       ;;
        status                  ) echo "${_zramInfo}"    ; exit 0 ;;
        config                  ) edit-conf                       ;;
    esac
else
    event-log "error" "This script must be run as root."
fi

exit 0
